# SPDX-License-Identifier: MIT
# Copyright: 2024-2026 NiceBots.xyz


services:
  redis:
    image: redis:alpine@sha256:bd999b5cfee25fb24b8320a31fddbd69f462df44c8138c66e369582937beebc0
    ports:
      - "6379:6379"
    command: --loglevel debug