#file: noinspection SpellCheckingInspection
name: CI/CD

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: ["main", "master", "dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: ./.github/workflows/quality.yaml

  docker:
    needs: quality
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yaml

  docs:
    if: github.repository == 'nicebots-xyz/botkit'
    needs: quality
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/docs.yaml

  deploy:
    if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
    needs: docker
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
