name: Check for LICENSE file header

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
    check-license-header:
        runs-on: ubuntu-latest
        steps:
        - name: Setup Copywrite
          uses: hashicorp/setup-copywrite@867a1a2a064a0626db322392806428f7dc59cb3e # v1.1.2
        - name: Check Config File
          run: test -f .copywrite.hcl
        - name: Check Header Compliance
          run: copywrite headers --plan --config .copywrite.hcl
