name: Check for LICENSE file header

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
    check-license-header:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Setup Copywrite
          uses: hashicorp/setup-copywrite@5e3e8a26d7b9f8a508848ad0a069dfd2f7aa5339
        - name: Check Header Compliance
          run: copywrite headers --plan --config .copywrite.hcl
