name: Check for LICENSE file header

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
    check-license-header:
        runs-on: ubuntu-latest
        steps:
        - name: Setup Copywrite
          uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3
        - name: Check Config File
          run: test -f .copywrite.hcl
        - name: Check Header Compliance
          run: copywrite headers --plan --config .copywrite.hcl
